ggplot(wins_tidy, aes(x=...1, fill=...1))+geom_bar()
mfv(wins_tidy$...1)
quantile(wins_tidy$Wins)
median(wins_tidy$Wins)
var(c(1,2,3,4,5))
sd(c(1,2,3,4,5))
cov(wins_tidy$Wins, wins_tidy$Total)
diff(range(wins_tidy$Wins))
mad(wins_tidy$Wins)
IQR(wins_tidy$Wins)